(function(){function C(){if(!w&&document.body){w=!0;var a=document.body,b=document.documentElement,d=window.innerHeight,c=a.scrollHeight;g=0<=document.compatMode.indexOf("CSS")?b:a;l=a;f.keyboardSupport&&window.addEventListener("keydown",Q,!1);if(top!=self)x=!0;else if(c>d&&(a.offsetHeight<=d||b.offsetHeight<=d)){var e=document.createElement("div");e.style.cssText="position:absolute; z-index:-10000; top:0; left:0; right:0; height:"+g.scrollHeight+"px";document.body.appendChild(e);var h,c=function(){h||
(h=setTimeout(function(){e.style.height="0";e.style.height=g.scrollHeight+"px";h=null},500))};setTimeout(c,10);D=new R(c);D.observe(a,{attributes:!0,childList:!0,characterData:!1});g.offsetHeight<=d&&(d=document.createElement("div"),d.style.clear="both",a.appendChild(d))}f.fixedBackground||(a.style.backgroundAttachment="scroll",b.style.backgroundAttachment="scroll")}}function E(a,b,d){S(b,d);if(1!=f.accelerationMax){var c=Date.now()-y;c<f.accelerationDelta&&(c=(1+50/c)/2,1<c&&(c=Math.min(c,f.accelerationMax),
b*=c,d*=c));y=Date.now()}r.push({x:b,y:d,lastX:0>b?.99:-.99,lastY:0>d?.99:-.99,start:Date.now()});if(!z){var e=a===document.body,h=function(c){c=Date.now();for(var g=0,k=0,l=0;l<r.length;l++){var n=r[l],p=c-n.start,m=p>=f.animationTime,q=m?1:p/f.animationTime;f.pulseAlgorithm&&(p=q,1<=p?q=1:0>=p?q=0:(1==f.pulseNormalize&&(f.pulseNormalize/=F(1)),q=F(p)));p=n.x*q-n.lastX>>0;q=n.y*q-n.lastY>>0;g+=p;k+=q;n.lastX+=p;n.lastY+=q;m&&(r.splice(l,1),l--)}e?window.scrollBy(g,k):(g&&(a.scrollLeft+=g),k&&(a.scrollTop+=
k));b||d||(r=[]);r.length?G(h,a,1E3/f.frameRate+1):z=!1};G(h,a,0);z=!0}}function T(a){w||C();var b=a.target,d=H(b);if(!d||a.defaultPrevented||a.ctrlKey||m(l,"embed")||m(b,"embed")&&/\.pdf/i.test(b.src)||m(l,"object"))return!0;var b=-a.wheelDeltaX||a.deltaX||0,c=-a.wheelDeltaY||a.deltaY||0;U&&(a.wheelDeltaX&&t(a.wheelDeltaX,120)&&(b=-120*(a.wheelDeltaX/Math.abs(a.wheelDeltaX))),a.wheelDeltaY&&t(a.wheelDeltaY,120)&&(c=-120*(a.wheelDeltaY/Math.abs(a.wheelDeltaY))));b||c||(c=-a.wheelDelta||0);1===a.deltaMode&&
(b*=40,c*=40);if(!f.touchpadSupport&&V(c))return!0;1.2<Math.abs(b)&&(b*=f.stepSize/120);1.2<Math.abs(c)&&(c*=f.stepSize/120);E(d,b,c);a.preventDefault();I()}function Q(a){var b=a.target,d=a.ctrlKey||a.altKey||a.metaKey||a.shiftKey&&a.keyCode!==h.spacebar;document.contains(l)||(l=document.activeElement);var c=/^(button|submit|radio|checkbox|file|color|image)$/i,e;if(!(e=/^(textarea|select|embed|object)$/i.test(b.nodeName)||m(b,"input")&&!c.test(b.type)||m(l,"video"))){e=a.target;var g=!1;if(-1!=document.URL.indexOf("www.youtube.com/watch")){do if(g=
e.classList&&e.classList.contains("html5-video-controls"))break;while(e=e.parentNode)}e=g}if(e||b.isContentEditable||a.defaultPrevented||d||(m(b,"button")||m(b,"input")&&c.test(b.type))&&a.keyCode===h.spacebar)return!0;e=b=0;d=H(l);c=d.clientHeight;d==document.body&&(c=window.innerHeight);switch(a.keyCode){case h.up:e=-f.arrowScroll;break;case h.down:e=f.arrowScroll;break;case h.spacebar:e=a.shiftKey?1:-1;e=-e*c*.9;break;case h.pageup:e=.9*-c;break;case h.pagedown:e=.9*c;break;case h.home:e=-d.scrollTop;
break;case h.end:c=d.scrollHeight-d.scrollTop-c;e=0<c?c+10:0;break;case h.left:b=-f.arrowScroll;break;case h.right:b=f.arrowScroll;break;default:return!0}E(d,b,e);a.preventDefault();I()}function W(a){l=a.target}function I(){clearTimeout(J);J=setInterval(function(){A={}},1E3)}function B(a,b){for(var d=a.length;d--;)A[K(a[d])]=b;return b}function H(a){var b=[],d=document.body,c=g.scrollHeight;do{var e=A[K(a)];if(e)return B(b,e);b.push(a);if(c===a.scrollHeight){if(e=L(g)&&L(d)||M(g),x&&g.clientHeight+
10<g.scrollHeight||!x&&e)return B(b,X())}else if(a.clientHeight+10<a.scrollHeight&&M(a))return B(b,a)}while(a=a.parentElement)}function L(a){return"hidden"!==getComputedStyle(a,"").getPropertyValue("overflow-y")}function M(a){a=getComputedStyle(a,"").getPropertyValue("overflow-y");return"scroll"===a||"auto"===a}function m(a,b){return(a.nodeName||"").toLowerCase()===b.toLowerCase()}function S(a,b){a=0<a?1:-1;b=0<b?1:-1;if(u.x!==a||u.y!==b)u.x=a,u.y=b,r=[],y=0}function V(a){if(a)return k.length||(k=
[a,a,a]),a=Math.abs(a),k.push(a),k.shift(),clearTimeout(N),N=setTimeout(function(){window.localStorage&&(localStorage.SS_deltaBuffer=k.join(","))},1E3),!O(120)&&!O(100)}function t(a,b){return Math.floor(a/b)==a/b}function O(a){return t(k[0],a)&&t(k[1],a)&&t(k[2],a)}function F(a){var b;a*=f.pulseScale;1>a?b=a-(1-Math.exp(-a)):(b=Math.exp(-1),--a,a=1-Math.exp(-a),b+=a*(1-b));return b*f.pulseNormalize}var P={frameRate:150,animationTime:400,stepSize:100,pulseAlgorithm:!0,pulseScale:4,pulseNormalize:1,
accelerationDelta:20,accelerationMax:1,keyboardSupport:!0,arrowScroll:100,touchpadSupport:!0,fixedBackground:!0,excluded:""},f=P,x=!1,u={x:0,y:0},w=!1,g=document.documentElement,l,D,k=[],U=/^Mac/.test(navigator.platform),h={left:37,up:38,right:39,down:40,spacebar:32,pageup:33,pagedown:34,end:35,home:36},f=P,r=[],z=!1,y=Date.now(),K=function(){var a=0;return function(b){return b.uniqueID||(b.uniqueID=a++)}}(),A={},J,N;window.localStorage&&localStorage.SS_deltaBuffer&&(k=localStorage.SS_deltaBuffer.split(","));
var G=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a,b,d){window.setTimeout(a,d||1E3/60)}}(),R=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,X=function(){var a;return function(){if(!a){var b=document.createElement("div");b.style.cssText="height:10000px;width:1px;";document.body.appendChild(b);var d=document.body.scrollTop;window.scrollBy(0,1);a=document.body.scrollTop!=d?document.body:
document.documentElement;window.scrollBy(0,-1);document.body.removeChild(b)}return a}}(),v;"onwheel"in document.createElement("div")?v="wheel":"onmousewheel"in document.createElement("div")&&(v="mousewheel");v&&(window.addEventListener(v,T,!1),window.addEventListener("mousedown",W,!1),window.addEventListener("load",C,!1))})();